### ISSUE TITLE
getblockhashes RPC call is missing

### ISSUE THREAD

**Issue by Tomas-M** [zcash-hackworks/zcash-patched-for-explorer#2]
And due to that, blockchain explorer is unable to show blocks.

**Comment by Tomas-M** [comment]
I confirmed that this fixed the issue.

**Comment by Tomas-M** [comment]
I've created a pull request to fix this
https://github.com/zcash-hackworks/zcash-patched-for-explorer/pull/3

**Comment by LarryRuane** [comment]
@daira, @mms710, @braddmiller, @ianamunoz: Should we merge this PR https://github.com/zcash-hackworks/zcash-patched-for-explorer/pull/3 quickly, or should we instead include the fix to this as part of https://github.com/zcash/zcash/issues/3708? It seems to me that we should review and merge this PR asap to get the currently-broken ZcashCo testnet explorer working. I don't have permission to add myself as a reviewer or to merge into hackworks.

**Comment by LarryRuane** [comment]
Closing, fixed by https://github.com/zcash-hackworks/zcash-patched-for-explorer/pull/3
